### ISSUE TITLE
Requires Logify >= 1.9.3

### ISSUE THREAD

**Issue by jacobamey** [theforeman/smart_proxy_chef#13]
Not sure if you would consider this an issue or not.

CentOS 6.x currently supports up to Ruby 1.8.7

When running a gem install smart_proxy_chef

I receive this error.

ERROR:  Error installing smart_proxy_chef:
logify requires Ruby version >= 1.9.3.

Its dependent on the Package Logify which requires a newer version of ruby then what is offically supported on CentOS 6.x

I'm going to see if simply upping my Ruby version does it for me with out breaking anything else. But something for you to be aware of, if you can decouple the dependencies from Logify that would be great for ease of install and future use.

**Comment by mmoll** [comment]
"Simply upping" is not possible, as foreman-proxy does rely on the correct system Ruby packages and won't work with RVM or similar (unless you're installing everything from gems under the new ruby, which bypasses even more system packaging...)

http://theforeman.org/plugins/foreman_chef/0.1/#1.1Supportedplatforms actually documents this, but is indeed a bit hidden. Maybe we should just delete the packages for unsupported platforms?

**Comment by jacobamey** [comment]
Oh thanks for the article, I work in the automotive field so change is slow unfortunately. With that being said we just brought CHEF in last year and only a few of us are up on it.

So I either up to CentOS 7 which is not supported officially at my location or move everyone to Puppet. Ha this will be fun in today's standup :-)

I'm thinking CentOS 7 it is. Especially since the only users would be my team. Now I get to hear gripes on systemd from the team.

Either way I think we are good here.

**Comment by mmoll** [comment]
Only the instance where the proxy is running on is required to move to CentOS 7, that might mitigate the shock a bit ;)

**Comment by jacobamey** [comment]
I secretly have been wanting to move everyone to 7... SHsss, don't tell them that.

**Comment by mmoll** [comment]
:no_mouth:
