### ISSUE TITLE
foreman_proxy doesn't start on foreman 1.12.0RC1

### ISSUE THREAD

**Issue by lbn-aaio-team** [theforeman/smart_proxy_chef#17]
Hello,

The smart_proxy does'nt start on Foreman 1.12.0 RC1. here the bug from proxy.log:
ERROR -- : Error during startup, terminating. uninitialized constant Proxy::Error::BadRequest
when configuring  :enabled: false on chef.yml, the proxy is starting.

hope this can help you :)
Best regards,

**Comment by ares** [comment]
Thanks for the report, I've copied it to the issue tracker, you can watch the progress at http://projects.theforeman.org/issues/15472
